### ISSUE TITLE
Could we use the dateparser library to allow arbitrary date formats? 

### ISSUE THREAD

**Issue by lwpulsifer** [MattiooFR/log-maker-100-days#1]
The `dateparser` library [(documentation)](https://dateparser.readthedocs.io/en/v0.3.4/) would allow for pretty much any date format, including relative dates, for the start of the journal.

**Comment by MattiooFR** [comment]
I just pushed a version with the dateparser library ! Great idea thanks !

**Comment by lwpulsifer** [comment]
Awesome! Marking this closed.
