### ISSUE TITLE
markdown2 library for converting to HTML?

### ISSUE THREAD

**Issue by lwpulsifer** [MattiooFR/log-maker-100-days#6]
Looks like this [library](https://github.com/trentm/python-markdown2) makes it really simple to convert markdown to html. The only question is how exactly we want to do this. Should there be another command line option which generates an html version of the log as a byproduct?

**Comment by MattiooFR** [comment]
I think less is more, and the less module we can have in this project, the more stable it will remains. Maybe we can use this to get the html and css code and then we can start from this to make our own. I'm doing a nanodegree on udacity on deeplearning on the same time so I might not be busy but I like the direction the project is taking 😃
