### ISSUE TITLE
Editing existing log files

### ISSUE THREAD

**Issue by lwpulsifer** [MattiooFR/log-maker-100-days#8]
@MattiooFR I'm going to take a stab at the editing existing log files in case of missing a day. I'm thinking I'll write a parser python file to parse an existing markdown file and then use that with a command line parameter to adjust in case of a missing day.

**Comment by MattiooFR** [comment]
Awesome, I have a good html doc format, I just need to do the routine to generate it. Let me know if you want me to collaborate in your branch for this issue !

**Comment by lwpulsifer** [comment]
@MattiooFR Please do! I'd love if you would take a look. I have a feeling I'm doing a lot more work than I need to be with my progress so far. At the moment, though, I can read in a log file and get the data from it pretty easily with some formatting tricks.

**Comment by lwpulsifer** [comment]
I've gotten a little stuck because I'm not sure how I want to update the file for missed days.

**Comment by MattiooFR** [comment]
I talked to you on the slack !
I was thinking to just remove the empty days, add the missing days at the end and update the whole table.

What do you think about that ?

**Comment by MattiooFR** [comment]
@lwpulsifer What's your twitter ? I want to tag you on my update tweet about this project !

**Comment by lwpulsifer** [comment]
@MattiooFR sorry to get to this so late! I'm not Twitter too much, but my handle is just LiamPulsifer.
