### ISSUE TITLE
Update days in the table when updating a log file

### ISSUE THREAD

**Issue by MattiooFR** [MattiooFR/log-maker-100-days#9]
I see that the log file is updating the days very well but the table (and the internal links) is still the same. I fixed some stuff (check my last commit on the update branch) but I dont have the time to work more on this, let me know if you have any questions on the changes that I made.

**Comment by lwpulsifer** [comment]
Yep, I'm on it -- didn't have time to work on the table and links yesterday.

**Comment by lwpulsifer** [comment]
@MattiooFR I have a working version up (uses the -u option with `main.py`), but it's horrifically ugly. I'm going to make some edits and improvements this weekend to make it really nice and concise before I make a pull request.

**Comment by lwpulsifer** [comment]
@MattiooFR take a look at the latest -- it's a lot less ugly, but still needs work. I have a feeling there's a way to do all of this much more elegantly.

**Comment by MattiooFR** [comment]
Great job @lwpulsifer ! I have merged your branch into master, and I will be working on updating an html log file during the next week !
